W2 ab101square
wedoforce/sf-dev-101-practice pull request #10
Opened 2022-02-10 08:58 UTC by SQuareKVK

maybe I finished this unit

2022-02-10 10:23 UTC, OleJoMan reviewed
what is this PR about?

2022-02-10 10:39 UTC, SQuareKVK commented
OMG
I was finished the lesson, but my PR to wrong brahch

2022-02-10 20:17 UTC, nchursin requested changes

2022-02-10 20:17 UTC, nchursin commented on LICENSE
> +                                 Apache License
Please, remove this file from the PR

- [x] Remove file

2022-02-10 20:17 UTC, nchursin commented on FAQ.md
> +# FAQ
Please remove this file from the PR

- [x] Remove file

2022-02-10 20:17 UTC, nchursin commented on README.md
> +=======
Please remvoe these changes from the PR

You can use `git fetch && git checkout origin/main README.md` to get the latest changes to your branch. Then commit the changes

- [ ] Remove changes

2022-02-10 20:17 UTC, nchursin commented on force-app/main/default/classes/tasks/BasicTasks.cls
> +    if (n == 0) {
Is it possible to get rid of this if statement? So that only a `while` loop handles everything

- [x] Do without the `if`

2022-02-10 20:17 UTC, nchursin commented on force-app/main/default/classes/tasks/CollectionsTasks.cls
> +      if (i == 0) {
Have you tried the additional task (without `if`)? Any issues you've faced?

2022-02-10 20:17 UTC, nchursin commented on force-app/main/default/classes/tasks/CollectionsTasks.cls
> +    return result;
This is a good approach from a maintenance perspective - you only have a single output point from the method.

But your loop continues to iterate, though the result is already here. You can use `break` to stop the loop execution.

- [x] Add `break` statement to stop iterating

2022-02-10 20:17 UTC, nchursin commented on force-app/main/default/classes/tasks/CollectionsTasks.cls
> +    Boolean b;
WIll provide feedback tomorrow morning :)

2022-02-10 20:17 UTC, nchursin commented on force-app/main/default/classes/tasks/CollectionsTasks.cls
> +    Integer resPriceTick;
Looks good 👍

2022-02-10 20:18 UTC, nchursin commented
Please rename the branch to be `lessons/W2AB101square`. This will trigger the autobuild

2022-02-11 06:06 UTC, baksale requested changes

2022-02-11 06:06 UTC, baksale commented on force-app/main/default/classes/tasks/CollectionsTasks.cls
> + **/
I saw this a lot in vendor's code.
I don't see much value in it, but extra lines consumption/to scroll.

Git has history of all changes. If I need to know who created the file or modified some line - I will be able to find this out (how often do I need to do this?)
However, these lines force me to look at it every time :)

Best practice: avoid such comments.
Read clean code book mentioned in the readings.

2022-02-11 06:06 UTC, baksale commented on force-app/main/default/classes/tasks/CollectionsTasks.cls
> +    Boolean b;
There is a hint: "an arbitrary collection"
listWithElementsToCheck.sort(); - sort inside will have extra loop, which violates the condition.

2022-02-11 06:06 UTC, baksale commented on force-app/main/default/classes/tasks/CollectionsTasks.cls
> +        return resPriceTick;
How to achieve same result from performance perspective and have only one return statement?

2022-02-11 06:27 UTC, SQuareKVK commented on LICENSE
> +                                 Apache License
Removed.

2022-02-12 09:39 UTC, baksale commented on .gitignore
> +.env
suggest to practice git and amend to not have this file in the PR.

2022-02-12 09:39 UTC, baksale commented on README.md
> -
suggest to practice git and amend to not have this file in the PR.

2022-02-12 09:39 UTC, baksale commented on force-app/main/default/classes/tasks/CollectionsTasks.cls
> +    Integer resPriceTick;
+

2022-02-12 14:23 UTC, SQuareKVK commented on .gitignore
> +.env
was delete
use git rm .gitignore

2022-02-12 14:24 UTC, SQuareKVK commented on README.md
> -
i use git rmREADME.md  11.02.22

2022-02-12 15:38 UTC, closed without merging

2022-02-12 15:40 UTC, SQuareKVK commented
I got confused in the edge - primarily with the git. he sent me over 100k updates. I close this request, delete everything physically and start again.

Damn it....