added my solution
wedoforce/sf-dev-101-practice pull request #43
Opened 2022-03-15 15:35 UTC by sergeyzhugan

2022-03-16 14:54 UTC, nchursin requested changes

2022-03-16 14:54 UTC, nchursin commented on force-app/main/default/classes/DML101.cls
> +    delete account;
You need to delete the account and the test contact here. At the moment you're only deleting the account

2022-03-17 09:17 UTC, sergeyzhugan commented on force-app/main/default/classes/DML101.cls
> +    delete account;
В задании task02 "Insert Contact for created in previous task Account with FirstName = 'Test' and LastName = 'Contact'"
я создал контакт связанный с Аккаунтом.
Если в задании task04 "Delete Test Contact and Account in one DML" имеется в ввиду удалить именно этот Контакт, то у меня он удаляется вместе с удалением связанного с ним Аккаунта

2022-03-17 11:21 UTC, nchursin commented on force-app/main/default/classes/DML101.cls
> +    delete account;
А, там каскадирование по умолчанию. Забыли об этом, когда делали задачу

Ок, есть идеи как просто любой контакт и любой аккаунт удалить за одну DML?

2022-03-17 12:21 UTC, sergeyzhugan commented on force-app/main/default/classes/DML101.cls
> +    delete account;
Идея следующая, но не проверял:
 List<sObject> sObjects = new List<sObject>();
sObjects.add(contact);
sObjects.add(accoutn);
delete sObjects;

2022-03-17 16:22 UTC, nchursin commented on force-app/main/default/classes/DML101.cls
> +    delete account;
Да, всё так

2022-03-17 16:22 UTC, nchursin approved these changes

2022-03-17 16:23 UTC, nchursin commented
done

2022-03-17 16:23 UTC, closed without merging